# Mini grid search for Random Forest
Chooose the best hyperparameters that fit gut microbe model

In [6]:
print(__doc__)

import numpy as np
import numpy as np
import scipy as sp
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from time import time
from scipy.stats import randint as sp_randint
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
%matplotlib inline 

Automatically created module for IPython interactive environment


In [9]:
train_gut = pd.read_csv('train_valid.csv')
X2 = train_gut[['SP1','SP2','SP3','SP4','SP5','SP6','SP7','SP8','SP9','SP10']].values
y = train_gut['Group'].values
from sklearn import cross_validation, linear_model
cv = cross_validation.ShuffleSplit(len(y), n_iter=50,test_size=0.3)

### Play with the n.estimates


In [18]:
rf_10 = RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1)  #n_estimator = 10
RF_10 = rf_10.fit(X2, y) #model fitting
scores_RF_10 = cross_validation.cross_val_score(RF_10,X2, y, cv=cv)
scores_RF_10.mean(), scores_RF_10.std()

(0.76342857142857146, 0.048162988584469678)

In [16]:
rf_50 = RandomForestClassifier(max_depth=5, n_estimators=50, max_features=1)  #n_estimator = 50
RF_50 = rf_50.fit(X2, y) #model fitting
scores_RF_50 = cross_validation.cross_val_score(RF_50,X2, y, cv=cv)
scores_RF_50.mean(), scores_RF_50.std()
## N_estimator = 50 seems to be the best
## Adding more 

(0.78514285714285714, 0.06187281226806475)

In [17]:
rf_100 = RandomForestClassifier(max_depth=5, n_estimators=100, max_features=1)  #n_estimator = 100
RF_100 = rf_100.fit(X2, y) #model fitting
scores_RF_100 = cross_validation.cross_val_score(RF_100,X2, y, cv=cv)
scores_RF_100.mean(), scores_RF_100.std()

(0.78685714285714281, 0.056340075271804978)

In [20]:
rf_1000 = RandomForestClassifier(max_depth=5, n_estimators=1000, max_features=1)  #n_estimator = 1000
RF_1000 = rf_1000.fit(X2, y) #model fitting
scores_RF_1000 = cross_validation.cross_val_score(RF_1000,X2, y, cv=cv)
scores_RF_1000.mean(), scores_RF_1000.std()

(0.80228571428571427, 0.060431104303553286)

### Play with max_depth

In [21]:
rf_50_MD = RandomForestClassifier(max_depth=None, n_estimators=50, max_features=1,)  #n_estimator = 50, max_depth = None
RF_50_MD = rf_50_MD.fit(X2, y) #model fitting
scores_RF_50_MD = cross_validation.cross_val_score(RF_50_MD,X2, y, cv=cv)
scores_RF_50_MD.mean(), scores_RF_50_MD.std()

## Max_depth = None is better than max_depth = 5

## Best model so far

(0.79828571428571427, 0.062180776608143411)

### Play with max_features

In [50]:
rf_50_auto = RandomForestClassifier(max_depth=None, n_estimators=50, max_features="auto") #max_features = auto  
RF_50_auto = rf_50_auto.fit(X2, y) #model fitting
scores_RF_50_auto = cross_validation.cross_val_score(RF_50_auto,X2, y, cv=cv)
scores_RF_50_auto.mean(), scores_RF_50_auto.std()
### This is the best model so far

(0.80971428571428572, 0.079305145624032361)

### Play with min_samples_split Default:min_samples_split=2

In [51]:
rf_50_ss_4 = RandomForestClassifier(max_depth=None, n_estimators=50, max_features="auto", min_samples_split=4) 
RF_50_ss_4 = rf_50_ss_4.fit(X2, y) #model fitting
scores_RF_50_ss_4 = cross_validation.cross_val_score(RF_50_ss_4,X2, y, cv=cv)
scores_RF_50_ss_4.mean(), scores_RF_50_ss_4.std()
##min_samples_split = 4, max_depth = None, n_estimators = 50, max_features = "auto" is the best set of parameters so far ##

(0.8114285714285715, 0.059109031044506259)

In [52]:
rf_50_ss_6 = RandomForestClassifier(max_depth=None, n_estimators=50, max_features="auto", min_samples_split=6) 
RF_50_ss_6 = rf_50_ss_6.fit(X2, y) #model fitting
scores_RF_50_ss_6 = cross_validation.cross_val_score(RF_50_ss_6,X2, y, cv=cv)
scores_RF_50_ss_6.mean(), scores_RF_50_ss_6.std()

(0.80514285714285705, 0.059847425055003692)

In [53]:
rf_50_ss_8 = RandomForestClassifier(max_depth=None, n_estimators=50, max_features="auto", min_samples_split=8) 
RF_50_ss_8 = rf_50_ss_8.fit(X2, y) #model fitting
scores_RF_50_ss_8 = cross_validation.cross_val_score(RF_50_ss_8,X2, y, cv=cv)
scores_RF_50_ss_8.mean(), scores_RF_50_ss_8.std()

(0.7897142857142857, 0.058765532032834016)

In [43]:
rf_50_ss_10 = RandomForestClassifier(max_depth=None, n_estimators=50, max_features="auto", min_samples_split=10) 
RF_50_ss_10 = rf_50_ss_10.fit(X2, y) #model fitting
scores_RF_50_ss_10 = cross_validation.cross_val_score(RF_50_ss_10,X2, y, cv=cv)
scores_RF_50_ss_10.mean(), scores_RF_50_ss_10.std()

(0.80285714285714282, 0.061078738075519841)

### Play with min_samples_leaf  # default = 1

In [58]:
rf_50_msl_2 = RandomForestClassifier(max_depth=None, n_estimators=50, max_features="auto", min_samples_split=4,min_samples_leaf = 2) 
RF_50_msl_2 = rf_50_msl_2.fit(X2, y) #model fitting
scores_RF_50_msl_2 = cross_validation.cross_val_score(RF_50_msl_2,X2, y, cv=cv)
scores_RF_50_msl_2.mean(), scores_RF_50_msl_2.std()

(0.79028571428571426, 0.051304612514920349)

In [65]:
rf_50_msl_3 = RandomForestClassifier(max_depth=None, n_estimators=50, max_features="auto", min_samples_split=4,min_samples_leaf = 3) 
RF_50_msl_3 = rf_50_msl_3.fit(X2, y) #model fitting
scores_RF_50_msl_3 = cross_validation.cross_val_score(RF_50_msl_3,X2, y, cv=cv)
scores_RF_50_msl_3.mean(), scores_RF_50_msl_3.std()

(0.79542857142857126, 0.056959706488581063)

In [66]:
rf_50_msl_4 = RandomForestClassifier(max_depth=None, n_estimators=50, max_features="auto", min_samples_split=4,min_samples_leaf = 4) 
RF_50_msl_4 = rf_50_msl_4.fit(X2, y) #model fitting
scores_RF_50_msl_4 = cross_validation.cross_val_score(RF_50_msl_4,X2, y, cv=cv)
scores_RF_50_msl_4.mean(), scores_RF_50_msl_4.std()
##min_samples_split = 4, max_depth = None, n_estimators = 50, max_features = "auto", min_samples_leaf = 4is the best set of parameters so far ##

(0.8045714285714286, 0.062950579903636145)

In [63]:
rf_50_msl_5 = RandomForestClassifier(max_depth=None, n_estimators=50, max_features="auto", min_samples_split=4,min_samples_leaf = 5) 
RF_50_msl_5 = rf_50_msl_5.fit(X2, y) #model fitting
scores_RF_50_msl_5 = cross_validation.cross_val_score(RF_50_msl_5,X2, y, cv=cv)
scores_RF_50_msl_5.mean(), scores_RF_50_msl_5.std()

(0.79942857142857138, 0.063757192471412455)

In [60]:
rf_50_msl_6 = RandomForestClassifier(max_depth=None, n_estimators=50, max_features="auto", min_samples_split=4,min_samples_leaf = 6) 
RF_50_msl_6 = rf_50_msl_6.fit(X2, y) #model fitting
scores_RF_50_msl_6 = cross_validation.cross_val_score(RF_50_msl_6,X2, y, cv=cv)
scores_RF_50_msl_6.mean(), scores_RF_50_msl_6.std()

(0.79199999999999993, 0.066157511489857379)

In [61]:
rf_50_msl_8 = RandomForestClassifier(max_depth=None, n_estimators=50, max_features="auto", min_samples_split=4,min_samples_leaf = 8) 
RF_50_msl_8 = rf_50_msl_8.fit(X2, y) #model fitting
scores_RF_50_msl_8 = cross_validation.cross_val_score(RF_50_msl_8,X2, y, cv=cv)
scores_RF_50_msl_8.mean(), scores_RF_50_msl_8.std()

(0.78514285714285714, 0.063436292966299046)

In [11]:
#### This is the final parameter to use after grid search
#### FINAL MODEL
#### FINAL MODEL

rf_final = RandomForestClassifier(max_depth=None, n_estimators=50, max_features= 1, min_samples_split=6,min_samples_leaf = 4, bootstrap=False, criterion='gini') 
RF_final = rf_final.fit(X2, y) #model fitting
scores_RF_final = cross_validation.cross_val_score(RF_final,X2, y, cv=cv)
scores_RF_final.mean(), scores_RF_final.std()

(0.81085714285714272, 0.049779923828050687)

Apply on Test data

In [67]:
bulk_test = pd.read_csv('gut_test.csv')
X2_bt = bulk_test[['SP1','SP2','SP3','SP4','SP5','SP6','SP7','SP8','SP9','SP10']].values
y_bt = bulk_test['Group'].values

In [70]:
print y_bt

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [91]:
print RF_50_msl_4.predict(X2_bt)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 0]


In [92]:
print RF_50_msl_4.predict_proba(X2_bt)

[[ 0.92876466  0.07123534]
 [ 0.91639337  0.08360663]
 [ 0.81619539  0.18380461]
 [ 0.83166321  0.16833679]
 [ 0.91185898  0.08814102]
 [ 0.76873077  0.23126923]
 [ 0.78468197  0.21531803]
 [ 0.86400506  0.13599494]
 [ 0.88295801  0.11704199]
 [ 0.75098583  0.24901417]
 [ 0.79137951  0.20862049]
 [ 0.8157332   0.1842668 ]
 [ 0.9124127   0.0875873 ]
 [ 0.90221521  0.09778479]
 [ 0.78520012  0.21479988]
 [ 0.79702918  0.20297082]
 [ 0.91798413  0.08201587]
 [ 0.7686668   0.2313332 ]
 [ 0.25975397  0.74024603]
 [ 0.28959354  0.71040646]
 [ 0.56359015  0.43640985]
 [ 0.17712377  0.82287623]
 [ 0.13110861  0.86889139]
 [ 0.57854063  0.42145937]
 [ 0.6472975   0.3527025 ]
 [ 0.35574353  0.64425647]
 [ 0.52064368  0.47935632]]


In [102]:
### on test set
cancer_chance = RF_50_msl_4.predict_proba(X2_bt)[:,0]
cancer_chance

array([ 0.92876466,  0.91639337,  0.81619539,  0.83166321,  0.91185898,
        0.76873077,  0.78468197,  0.86400506,  0.88295801,  0.75098583,
        0.79137951,  0.8157332 ,  0.9124127 ,  0.90221521,  0.78520012,
        0.79702918,  0.91798413,  0.7686668 ,  0.25975397,  0.28959354,
        0.56359015,  0.17712377,  0.13110861,  0.57854063,  0.6472975 ,
        0.35574353,  0.52064368])

In [155]:
###Since we want to reduce the false negative level, we need to set the threshold higher
###The first number higher than 0.7 is the new cutoff for put the prediction value as 0
### if RF_50_msl_4.predict_proba(X2_bt)[:,0]>0.7, y_predict = 0; if RF_50_msl_4.predict_proba(X2_bt)[:,0]<=0.7, y_predict =1

cancer_bin_l = []
for x in np.nditer(cancer_chance):
    if x > 0.7:
        y = 0
    else:
        y = 1
    #print y
    cancer_bin_l.append(y)
import numpy as np
cancer_predict = np.asarray(cancer_bin_l)
print cancer_predict
#print cancer_chance

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1]


In [159]:
#acc = (y_bt == RF_50_msl_4.predict(X2_bt))
acc = (y_bt == cancer_predict)
#RF.predict(X2_bt)
print np.mean(acc)
acc

0.962962962963


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [169]:
#### On training sets
#print RF_50_msl_4.predict_proba(X2)
cancer_chance_train = RF_50_msl_4.predict_proba(X2)[:,0]
#print cancer_chance_train
cancer_bin_train_l = []
for x in np.nditer(cancer_chance_train):
    if x > 0.7:
        y = 0
    else:
        y = 1
    #print y
    cancer_bin_train_l.append(y)
#print cancer_bin_train_l
import numpy as np
cancer_predict_train = np.asarray(cancer_bin_train_l)
print cancer_predict_train

[0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 1 0]


In [181]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [182]:
cancer_predict_train

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0])

In [1]:
acc2 = (y == cancer_predict_train)
print np.mean(acc2)

NameError: name 'y' is not defined